
-- Add multilingual and extended fields to tours table
ALTER TABLE public.tours 
  ADD COLUMN IF NOT EXISTS title_ru TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS title_es TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS title_ar TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS description_ru TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS description_es TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS description_ar TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS difficulty TEXT NOT NULL DEFAULT 'Easy',
  ADD COLUMN IF NOT EXISTS max_people INTEGER NOT NULL DEFAULT 20,
  ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS is_featured BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS category TEXT NOT NULL DEFAULT 'Tour Package',
  ADD COLUMN IF NOT EXISTS currency TEXT NOT NULL DEFAULT 'USD',
  ADD COLUMN IF NOT EXISTS gallery_images TEXT[] NOT NULL DEFAULT '{}';
